version: '3.8'

services:

  db:
    image: postgres:12.4
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - diploma_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
      timeout: 3s
      retries: 15

  api:
    image: ${DOCKERHUB_USERNAME}/diploma_10:${TAG_NAME}
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_HOST: db
      DEBUG: True
#    depends_on:
#      db:
#        condition: service_healthy

  collect_static:
    image: ${DOCKERHUB_USERNAME}/todolist:${TAG_NAME}
    build: .
    env_file:
      - .env
    entrypoint: ''
    command: python3 manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/static

  frontend:
      image: sermalenk/skypro-front:lesson-38
      platform: linux/amd64
      restart: always
      ports:
        - "80:80"
#      depends_on:
#        api:
#          condition: service_healthy
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        - django_static:/usr/share/nginx/html/static/

  bot:
    image: ${DOCKERHUB_USERNAME}/diploma_10:${TAG_NAME}
    build: .
    platform: linux/amd64
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
#    depends_on:
#      db:
#        condition: service_healthy
#      api:
#        condition: service_healthy
    volumes:
      - ./todolist/bot/:/opt/todolist/bot/
    command: python3 manage.py runbot


volumes:
  diploma_pg_data:
  django_static:
