# Generated by Django 4.1.7 on 2023-03-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_tg_user_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='Chat ID'),
        ),
    ]
